# Generated by Django 3.2.6 on 2021-09-10 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registrousuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registrousuarios.models.custom_upload_to)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
