# Generated by Django 3.2.6 on 2021-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrousuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12, verbose_name='Saldo'),
        ),
    ]
