# Generated by Django 3.2.6 on 2021-09-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='IdUsuario',
            new_name='idUsuario',
        ),
    ]
